### ISSUE TITLE
Bundling webpack with IsomorphicRelay

### ISSUE THREAD

**Issue by alewaros** [denvned/isomorphic-relay#12]
I am using isomorphic relay and integrated webpack for the node server with babel and the relay-babel-plugin. It all works well when I load the page the first time, the second one it crashes with the following error.

```
ReferenceError: document is not defined
    at getActiveElement (/Users/AJ/Desktop/winebox/app/build/index.js:17061:13)
    at ReactReconcileTransaction.ReactInputSelection.getSelectionInformation (/Users/AJ/Desktop/winebox/app/build/index.js:16650:24)
    at ReactReconcileTransaction.Mixin.initializeAll (/Users/AJ/Desktop/winebox/app/build/index.js:4477:76)
    at ReactReconcileTransaction.Mixin.perform (/Users/AJ/Desktop/winebox/app/build/index.js:4444:13)
    at ReactUpdatesFlushTransaction.Mixin.perform (/Users/AJ/Desktop/winebox/app/build/index.js:4445:21)
    at ReactUpdatesFlushTransaction.assign.perform (/Users/AJ/Desktop/winebox/app/build/index.js:3677:39)
    at Object.flushBatchedUpdates (/Users/AJ/Desktop/winebox/app/build/index.js:3738:20)
    at Object.wrapper [as flushBatchedUpdates] (/Users/AJ/Desktop/winebox/app/build/index.js:3983:22)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Users/AJ/Desktop/winebox/app/build/index.js:4511:26)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/AJ/Desktop/winebox/app/build/index.js:4458:17)
```

I have it narrowed down to the portion that creates the `reactOutput` in the render function.

```
const reactOutput = ReactDOMServer.renderToString(
      <IsomorphicRelay.RootContainer {...rootContainerProps} />
    );
```

Is there a way to fix this? Thanks in advance for any help

**Comment by denvned** [comment]
Your stack trace is too short to be useful. You can write `Error.stackTraceLimit = 1000;` in the top of the entry script to make it bigger.

**Comment by alewaros** [comment]
This is the entire stack trace.

```
ReferenceError: document is not defined
    at getActiveElement (/Users/AJ/Desktop/winebox/app/build/index.js:17062:13)
    at ReactReconcileTransaction.ReactInputSelection.getSelectionInformation (/Users/AJ/Desktop/winebox/app/build/index.js:16651:24)
    at ReactReconcileTransaction.Mixin.initializeAll (/Users/AJ/Desktop/winebox/app/build/index.js:4478:76)
    at ReactReconcileTransaction.Mixin.perform (/Users/AJ/Desktop/winebox/app/build/index.js:4445:13)
    at ReactUpdatesFlushTransaction.Mixin.perform (/Users/AJ/Desktop/winebox/app/build/index.js:4446:21)
    at ReactUpdatesFlushTransaction.assign.perform (/Users/AJ/Desktop/winebox/app/build/index.js:3678:39)
    at Object.flushBatchedUpdates (/Users/AJ/Desktop/winebox/app/build/index.js:3739:20)
    at Object.wrapper [as flushBatchedUpdates] (/Users/AJ/Desktop/winebox/app/build/index.js:3984:22)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Users/AJ/Desktop/winebox/app/build/index.js:4512:26)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/AJ/Desktop/winebox/app/build/index.js:4459:17)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/AJ/Desktop/winebox/app/build/index.js:10998:20)
    at Object.enqueueUpdate (/Users/AJ/Desktop/winebox/app/build/index.js:3768:23)
    at enqueueUpdate (/Users/AJ/Desktop/winebox/app/build/index.js:7475:17)
    at Object.ReactUpdateQueue.enqueueSetState (/Users/AJ/Desktop/winebox/app/build/index.js:7641:6)
    at RelayContainer.ReactComponent.setState (/Users/AJ/Desktop/winebox/app/node_modules/react/lib/ReactComponent.js:65:16)
    at RelayContainer._handleFragmentDataUpdate (/Users/AJ/Desktop/winebox/app/node_modules/react-relay/lib/RelayContainer.js:398:12)
    at GraphQLStoreSingleQueryResolver._handleChange (/Users/AJ/Desktop/winebox/app/node_modules/react-relay/lib/GraphQLStoreQueryResolver.js:249:12)
    at Object.ErrorUtils.applyWithGuard (/Users/AJ/Desktop/winebox/app/node_modules/react-relay/node_modules/fbjs/lib/ErrorUtils.js:18:21)
    at GraphQLStoreChangeEmitter._processSubscriber (/Users/AJ/Desktop/winebox/app/node_modules/react-relay/lib/GraphQLStoreChangeEmitter.js:119:22)
    at /Users/AJ/Desktop/winebox/app/node_modules/react-relay/lib/GraphQLStoreChangeEmitter.js:103:21
    at Array.forEach (native)
    at GraphQLStoreChangeEmitter._processSubscribers (/Users/AJ/Desktop/winebox/app/node_modules/react-relay/lib/GraphQLStoreChangeEmitter.js:102:23)
    at /Users/AJ/Desktop/winebox/app/node_modules/react-relay/lib/GraphQLStoreChangeEmitter.js:89:23
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/AJ/Desktop/winebox/app/node_modules/react/lib/Transaction.js:136:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/AJ/Desktop/winebox/app/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
    at GraphQLStoreChangeEmitter.batchedUpdates [as _batchUpdate] (/Users/AJ/Desktop/winebox/app/node_modules/react/lib/ReactUpdates.js:94:20)
    at GraphQLStoreChangeEmitter._processBroadcasts (/Users/AJ/Desktop/winebox/app/node_modules/react-relay/lib/GraphQLStoreChangeEmitter.js:88:12)
    at /Users/AJ/Desktop/winebox/app/node_modules/react-relay/lib/GraphQLStoreChangeEmitter.js:69:23
    at tryCallOne (/Users/AJ/Desktop/winebox/app/node_modules/promise/lib/core.js:37:12)
    at /Users/AJ/Desktop/winebox/app/node_modules/promise/lib/core.js:123:15
    at flush (/Users/AJ/Desktop/winebox/app/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)
```

Thank you for the quick support.

**Comment by denvned** [comment]
Looks like you didn't inject the no-op batching strategy:

``` js
RelayStoreData.getDefaultInstance().getChangeEmitter().injectBatchingStrategy(() => {});
```

**Comment by AJShippify** [comment]
I do have that line, most of the implementation was made following the Star Wars example.

Would it help if I shared some implementation code?

**Comment by alewaros** [comment]
Sorry about that, just noticed I used my other account while I was at work. Could the fact that webpack needs for the server-side target to be set to 'node' the reason that it fails to define the document variable?

**Comment by denvned** [comment]
> Could the fact that webpack needs for the server-side target to be set to 'node' the reason that it fails to define the document variable?

The problem is that no-op batching strategy is not properly injected. Anyway, you definitely should use `node` as the target for the server side bundle, that might solve the problem. See https://github.com/denvned/isomorphic-relay-router/issues/5#issuecomment-156984817 and https://github.com/denvned/isomorphic-relay/issues/9#issuecomment-166942629

**Comment by alewaros** [comment]
Good news, I updated the react and react-relay libraries and the error disappeared. Thanks a lot for the help.
